In [1]:
# Import dependencies 
import pandas as pd
import datetime

In [3]:
# Read in csv
df = pd.read_csv("../Data/us_disaster_declarations.csv")
df

,fema_declaration_string,disaster_number,state,declaration_type,declaration_date,fy_declared,incident_type,declaration_title,ih_program_declared,ia_program_declared,...,incident_begin_date,incident_end_date,disaster_closeout_date,fips,place_code,designated_area,declaration_request_number,hash,last_refresh,id
0,DR-1-GA,1,GA,DR,1953-05-02T00:00:00Z,1953,Tornado,Tornado,0,1,...,1953-05-02T00:00:00Z,1953-05-02T00:00:00Z,1954-06-01T00:00:00Z,13000,0,Statewide,53013,bb121323c9c29d3bef0c9a3f134bfd8b5ecff148,2021-07-13T23:01:19Z,60c3b7a9a0ee349d71025780
1,DR-2-TX,2,TX,DR,1953-05-15T00:00:00Z,1953,Tornado,Tornado & Heavy Rainfall,0,1,...,1953-05-15T00:00:00Z,1953-05-15T00:00:00Z,1958-01-01T00:00:00Z,48000,0,Statewide,53003,c879557e78d059e6847e7688388c339d10f51979,2021-07-13T23:01:19Z,60c3b7a9a0ee349d71025783
2,DR-3-LA,3,LA,DR,1953-05-29T00:00:00Z,1953,Flood,Flood,0,1,...,1953-05-29T00:00:00Z,1953-05-29T00:00:00Z,1960-02-01T00:00:00Z,22000,0,Statewide,53005,4fb19699fdbba1387ffa2263fcc4a4e37a1de6d6,2021-07-13T23:01:19Z,60c3b7a9a0ee349d71025777
3,DR-4-MI,4,MI,DR,1953-06-02T00:00:00Z,1953,Tornado,Tornado,0,1,...,1953-06-02T00:00:00Z,1953-06-02T00:00:00Z,1956-02-01T00:00:00Z,26000,0,Statewide,53004,87a0c1dd5da249767f545e0c0a43f917e4e9ca83,2021-07-13T23:01:19Z,60c3b7a9a0ee349d7102577a
4,DR-5-MT,5,MT,DR,1953-06-06T00:00:00Z,1953,Flood,Floods,0,1,...,1953-06-06T00:00:00Z,1953-06-06T00:00:00Z,1955-12-01T00:00:00Z,30000,0,Statewide,53006,954449c15634fb45c8bea3ac975782793ccde050,2021-07-13T23:01:19Z,60c3b7a9a0ee349d71025774
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
62107,DR-4610-CA,4610,CA,DR,2021-08-24T20:45:00Z,2021,Fire,Wildfires,1,0,...,2021-07-14T00:00:00Z,NaN,NaN,6063,99063,Plumas (County),21087,d615785ddbaca2e0dbb66805d84246680c86f560,2021-08-25T02:21:43Z,6125a937434e34d5ee5cd8af
62108,DR-4610-CA,4610,CA,DR,2021-08-24T20:45:00Z,2021,Fire,Wildfires,1,0,...,2021-07-14T00:00:00Z,NaN,NaN,6061,99061,Placer (County),21087,6e1ab1c91a9838148684d35413b598c5ea66df71,2021-08-25T02:21:43Z,6125a937434e34d5ee5cd8b6
62109,DR-4610-CA,4610,CA,DR,2021-08-24T20:45:00Z,2021,Fire,Wildfires,1,0,...,2021-07-14T00:00:00Z,NaN,NaN,6035,99035,Lassen (County),21087,74f77c93f158659bf1dd9f871227a9993244478d,2021-08-25T02:21:43Z,6125a937434e34d5ee5cd8a3
62110,DR-4610-CA,4610,CA,DR,2021-08-24T20:45:00Z,2021,Fire,Wildfires,1,0,...,2021-07-14T00:00:00Z,NaN,NaN,6057,99057,Nevada (County),21087,dde89f65556f220034ac16cfa66abf7d135962da,2021-08-25T02:21:43Z,6125a937434e34d5ee5cd8c1
62111,FM-5416-CA,5416,CA,FM,2021-08-25T00:53:00Z,2021,Fire,French Fire,0,0,...,2021-08-24T23:22:00Z,NaN,NaN,6029,99029,Kern (County),21088,b2120fdada11e2ceefe3714927afe2443c719812,2021-08-25T16:22:54Z,61266e5e434e34d5eee6f25e

In [4]:
df["declaration_date"] = pd.to_datetime(df["declaration_date"]).dt.date

In [5]:
df.head()

,fema_declaration_string,disaster_number,state,declaration_type,declaration_date,fy_declared,incident_type,declaration_title,ih_program_declared,ia_program_declared,...,incident_begin_date,incident_end_date,disaster_closeout_date,fips,place_code,designated_area,declaration_request_number,hash,last_refresh,id
0,DR-1-GA,1,GA,DR,1953-05-02,1953,Tornado,Tornado,0,1,...,1953-05-02T00:00:00Z,1953-05-02T00:00:00Z,1954-06-01T00:00:00Z,13000,0,Statewide,53013,bb121323c9c29d3bef0c9a3f134bfd8b5ecff148,2021-07-13T23:01:19Z,60c3b7a9a0ee349d71025780
1,DR-2-TX,2,TX,DR,1953-05-15,1953,Tornado,Tornado & Heavy Rainfall,0,1,...,1953-05-15T00:00:00Z,1953-05-15T00:00:00Z,1958-01-01T00:00:00Z,48000,0,Statewide,53003,c879557e78d059e6847e7688388c339d10f51979,2021-07-13T23:01:19Z,60c3b7a9a0ee349d71025783
2,DR-3-LA,3,LA,DR,1953-05-29,1953,Flood,Flood,0,1,...,1953-05-29T00:00:00Z,1953-05-29T00:00:00Z,1960-02-01T00:00:00Z,22000,0,Statewide,53005,4fb19699fdbba1387ffa2263fcc4a4e37a1de6d6,2021-07-13T23:01:19Z,60c3b7a9a0ee349d71025777
3,DR-4-MI,4,MI,DR,1953-06-02,1953,Tornado,Tornado,0,1,...,1953-06-02T00:00:00Z,1953-06-02T00:00:00Z,1956-02-01T00:00:00Z,26000,0,Statewide,53004,87a0c1dd5da249767f545e0c0a43f917e4e9ca83,2021-07-13T23:01:19Z,60c3b7a9a0ee349d7102577a
4,DR-5-MT,5,MT,DR,1953-06-06,1953,Flood,Floods,0,1,...,1953-06-06T00:00:00Z,1953-06-06T00:00:00Z,1955-12-01T00:00:00Z,30000,0,Statewide,53006,954449c15634fb45c8bea3ac975782793ccde050,2021-07-13T23:01:19Z,60c3b7a9a0ee349d71025774

In [6]:
df["declaration_date"] = pd.to_datetime(df["declaration_date"])

In [7]:
df["incident_begin_date"] = pd.to_datetime(df["incident_begin_date"]).dt.date

In [8]:
df["incident_begin_date"] = pd.to_datetime(df["incident_begin_date"])

In [9]:
df.dtypes

fema_declaration_string               object
disaster_number                        int64
state                                 object
declaration_type                      object
declaration_date              datetime64[ns]
fy_declared                            int64
incident_type                         object
declaration_title                     object
ih_program_declared                    int64
ia_program_declared                    int64
pa_program_declared                    int64
hm_program_declared                    int64
incident_begin_date           datetime64[ns]
incident_end_date                     object
disaster_closeout_date                object
fips                                   int64
place_code                             int64
designated_area                       object
declaration_request_number             int64
hash                                  object
last_refresh                          object
id                                    object
dtype: object

In [10]:
# remove last refresh
# convert columns to datetypes
# drop na's

In [11]:
df.isna().sum()

fema_declaration_string           0
disaster_number                   0
state                             0
declaration_type                  0
declaration_date                  0
fy_declared                       0
incident_type                     0
declaration_title                 0
ih_program_declared               0
ia_program_declared               0
pa_program_declared               0
hm_program_declared               0
incident_begin_date               0
incident_end_date              8513
disaster_closeout_date        15239
fips                              0
place_code                        0
designated_area                   0
declaration_request_number        0
hash                              0
last_refresh                      0
id                                0
dtype: int64

In [12]:
# might not be able to look at length of disaster

In [13]:
df = df.drop(["incident_end_date", "disaster_closeout_date"], axis=1)

In [14]:
df.isna().sum()

fema_declaration_string       0
disaster_number               0
state                         0
declaration_type              0
declaration_date              0
fy_declared                   0
incident_type                 0
declaration_title             0
ih_program_declared           0
ia_program_declared           0
pa_program_declared           0
hm_program_declared           0
incident_begin_date           0
fips                          0
place_code                    0
designated_area               0
declaration_request_number    0
hash                          0
last_refresh                  0
id                            0
dtype: int64

In [15]:
# Number of natural diasters by state
df.groupby(["state"]).size()

state
AK     302
AL    1650
AR    1588
AS      75
AZ     327
CA    1455
CO     644
CT     248
DC      23
DE      52
FL    2088
FM      31
GA    2269
GU      19
HI      98
IA    1823
ID     357
IL    1268
IN    1451
KS    1682
KY    2511
LA    2301
MA     393
MD     448
ME    1010
MH      53
MI     793
MN    1498
MO    2670
MP      63
MS    1736
MT     597
NC    1984
ND    1303
NE    1423
NH     294
NJ     583
NM     500
NV     273
NY    1448
OH    1281
OK    2461
OR     583
PA    1226
PR    1826
PW       1
RI     108
SC     855
SD    1382
TN    1565
TX    5164
UT     249
VA    2493
VI      79
VT     328
WA     930
WI     892
WV    1230
WY     128
dtype: int64

In [16]:
#59 states? - incudles US territories
len(df.groupby(["state"]).size())

59

In [17]:
# number of incidents by type
df.groupby(["incident_type"]).size()

incident_type
Biological           7853
Chemical                9
Coastal Storm         570
Dam/Levee Break        13
Drought              1292
Earthquake            227
Fire                 3547
Fishing Losses         42
Flood               10461
Freezing              301
Human Cause             7
Hurricane           12085
Mud/Landslide          36
Other                 306
Severe Ice Storm     2942
Severe Storm(s)     17065
Snow                 3664
Terrorist               5
Tornado              1488
Toxic Substances        9
Tsunami                 9
Typhoon               130
Volcano                51
dtype: int64

In [18]:
df.drop(df[df["incident_type"]=="Other"].index, inplace = True)

In [19]:
df.groupby(["incident_type"]).size()

incident_type
Biological           7853
Chemical                9
Coastal Storm         570
Dam/Levee Break        13
Drought              1292
Earthquake            227
Fire                 3547
Fishing Losses         42
Flood               10461
Freezing              301
Human Cause             7
Hurricane           12085
Mud/Landslide          36
Severe Ice Storm     2942
Severe Storm(s)     17065
Snow                 3664
Terrorist               5
Tornado              1488
Toxic Substances        9
Tsunami                 9
Typhoon               130
Volcano                51
dtype: int64

In [20]:
df = df[df.incident_type!="Biological"]
df.head()

,fema_declaration_string,disaster_number,state,declaration_type,declaration_date,fy_declared,incident_type,declaration_title,ih_program_declared,ia_program_declared,pa_program_declared,hm_program_declared,incident_begin_date,fips,place_code,designated_area,declaration_request_number,hash,last_refresh,id
0,DR-1-GA,1,GA,DR,1953-05-02,1953,Tornado,Tornado,0,1,1,1,1953-05-02,13000,0,Statewide,53013,bb121323c9c29d3bef0c9a3f134bfd8b5ecff148,2021-07-13T23:01:19Z,60c3b7a9a0ee349d71025780
1,DR-2-TX,2,TX,DR,1953-05-15,1953,Tornado,Tornado & Heavy Rainfall,0,1,1,1,1953-05-15,48000,0,Statewide,53003,c879557e78d059e6847e7688388c339d10f51979,2021-07-13T23:01:19Z,60c3b7a9a0ee349d71025783
2,DR-3-LA,3,LA,DR,1953-05-29,1953,Flood,Flood,0,1,1,1,1953-05-29,22000,0,Statewide,53005,4fb19699fdbba1387ffa2263fcc4a4e37a1de6d6,2021-07-13T23:01:19Z,60c3b7a9a0ee349d71025777
3,DR-4-MI,4,MI,DR,1953-06-02,1953,Tornado,Tornado,0,1,1,1,1953-06-02,26000,0,Statewide,53004,87a0c1dd5da249767f545e0c0a43f917e4e9ca83,2021-07-13T23:01:19Z,60c3b7a9a0ee349d7102577a
4,DR-5-MT,5,MT,DR,1953-06-06,1953,Flood,Floods,0,1,1,1,1953-06-06,30000,0,Statewide,53006,954449c15634fb45c8bea3ac975782793ccde050,2021-07-13T23:01:19Z,60c3b7a9a0ee349d71025774

In [22]:
df.to_csv("../Data/diaster_data_clean.csv", index = False)