In [5]:
import boto3
import pandas as pd

s3_client = boto3.client('s3')

In [6]:
path = 's3://s3disastersbuket/temp_disaster_merge_new.csv'

In [7]:
df = pd.read_csv(path)

In [8]:
df.head()

,disaster_number,STATE,declaration_type,declaration_date,fy_declared,incident_type,declaration_title,fips,place_code,designated_area,...,month_x,month_year,TEMPERATURE_ID,DATE,Country,Fahrenheit,AverageTemperatureF,AverageTemperatureUncertaintyF,year_y,month_y
0,1796,AK,DR,2008-09-26,2008,Severe Storm(s),"Severe Storms, Flooding, Landslides, And Mudsl...",2090,99090,Fairbanks North Star (Borough),...,9,2008-09,1398,2008-09-01,United States,74.696,40.5392,32.4518,2008,9
1,1796,AK,DR,2008-09-26,2008,Severe Storm(s),"Severe Storms, Flooding, Landslides, And Mudsl...",2068,99068,Denali (Borough),...,9,2008-09,1398,2008-09-01,United States,74.696,40.5392,32.4518,2008,9
2,1796,AK,DR,2008-09-26,2008,Severe Storm(s),"Severe Storms, Flooding, Landslides, And Mudsl...",2185,99185,North Slope (Borough),...,9,2008-09,1398,2008-09-01,United States,74.696,40.5392,32.4518,2008,9
3,1796,AK,DR,2008-09-26,2008,Severe Storm(s),"Severe Storms, Flooding, Landslides, And Mudsl...",2290,86650,Yukon Koyukuk Regional Educational Attendance ...,...,9,2008-09,1398,2008-09-01,United States,74.696,40.5392,32.4518,2008,9
4,1440,AK,DR,2002-11-08,2003,Earthquake,Earthquake,2170,99170,Matanuska-Susitna (Borough),...,11,2002-11,1328,2002-11-01,United States,-27.373,20.1254,32.4266,2002,11